import {
  BasilisksBelt,
  BlackDistortionEarring,
  CentaurusBelt,
  DawnEarring,
  DeborekaBelt,
  DeborekaEarring,
  DeborekaNecklace,
  EtherealEarring,
  EyeOfTheRuinsRing,
  ForestRonarosRing,
  LaytennsPowerStone,
  OgreRing,
  OminousRing,
  OrkinradsBelt,
  RevivedLunarNecklace,
  RevivedRiverNecklace,
  RingOfCadryGuardian,
  RingOfCrescentGuardian,
  SerapsNecklace,
  SicilsNecklace,
  TungradBelt,
  TungradEarring,
  TungradNecklace,
  TurosBelt,
  VahasDawn,
  ValtarraEclipsedBelt,
} from "../assets/icons";

const items = [
  { id: 12031, name: "三日月守護者のリング", icon: RingOfCrescentGuardian },
  { id: 11653, name: "デヴォレカネックレス", icon: DeborekaNecklace },
  { id: 11629, name: "ツングラドのネックレス", icon: TungradNecklace },
  { id: 11853, name: "黒い侵食のイヤリング", icon: BlackDistortionEarring },
  { id: 12032, name: "カドリー守護者のリング", icon: RingOfCadryGuardian },
  { id: 12042, name: "フォレストロナロスのリング", icon: ForestRonarosRing },
  { id: 12060, name: "廃墟の瞳リング", icon: EyeOfTheRuinsRing },
  { id: 12061, name: "ツングラドのリング", icon: TungradEarring },
  { id: 12068, name: "不気味な背後のリング", icon: OminousRing },
  { id: 11609, name: "オーガのリング", icon: OgreRing },
  { id: 11625, name: "シチルのネックレス", icon: SicilsNecklace },
  { id: 11628, name: "セラフのネックレス", icon: SerapsNecklace },
  { id: 11629, name: "ツングラドのネックレス", icon: TungradNecklace },
  { id: 11630, name: "ライテンの動力石", icon: LaytennsPowerStone },
  { id: 11662, name: "目覚めた川のネックレス", icon: RevivedRiverNecklace },
  { id: 11663, name: "目覚めた月のネックレス", icon: RevivedLunarNecklace },
  { id: 11828, name: "ツングラドのイヤリング", icon: TungradEarring },
  { id: 11855, name: "黎明のイヤリング", icon: DawnEarring },
  { id: 11856, name: "夢幻のイヤリング", icon: EtherealEarring },
  { id: 11875, name: "バアの暁", icon: VahasDawn },
  { id: 11882, name: "デヴォレカイヤリング", icon: DeborekaEarring },
  { id: 12229, name: "ケンタウロスのベルト", icon: CentaurusBelt },
  { id: 12230, name: "バジリスクのベルト", icon: BasilisksBelt },
  { id: 12236, name: "バルタラの隠れた光ベルト", icon: ValtarraEclipsedBelt },
  { id: 12237, name: "ツングラドのベルト", icon: TungradBelt },
  { id: 12251, name: "オルキンラドのベルト", icon: OrkinradsBelt },
  { id: 12257, name: "トゥーロのベルト", icon: TurosBelt },
  { id: 12282, name: "デヴォレカベルト", icon: DeborekaBelt },
];

export { items };
